### ISSUE TITLE
Implement Documentation(Landing, Integration, Authentication, SDK & Plugins) Page Design

### ISSUE THREAD

**Issue by Waeyword** [zuri-training/Team-29_PriceCompare#128]

**Comment by Iam-Rey** [comment]
All documentation pages have been done.

**Comment by Iam-Rey** [comment]
![Documentation Page - Google Chrome 8_15_2022 3_24_13 AM](https://user-images.githubusercontent.com/105178384/184619385-8b89f6e9-ed81-4adb-bd09-5f2eba6f114d.png)

Desktop View of Documentation Home page
