### ISSUE TITLE
Create Page Footers

### ISSUE THREAD

**Issue by Waeyword** [zuri-training/Team-29_PriceCompare#17]

**Comment by ireSeun** [comment]
Created both the lofi and hi fi footer using the primary and secondary colour, then made it a component for easy use by the design team.
![Footer Hifi (1)](https://user-images.githubusercontent.com/82669341/182262973-9717e61d-b302-4282-8329-e0bc143267a3.png)
![Footer Lofi](https://user-images.githubusercontent.com/82669341/182262989-a7283da2-18be-44e1-8e1f-9f15739244cb.png)
