### ISSUE TITLE
Implement Contact Page Design

### ISSUE THREAD

**Issue by Waeyword** [zuri-training/Team-29_PriceCompare#20]

**Comment by Laurrencia** [comment]
implement contact page design, and mobile responsive design for header, footer and privacy policy page

**Comment by Laurrencia** [comment]
implemented the contact page design for both desktop view and mobile view 
![contactpage desktop](https://user-images.githubusercontent.com/81080746/183879298-ccef7a52-df36-4475-9ff1-f4c734fbc437.png)
![contactpagedesktop2](https://user-images.githubusercontent.com/81080746/183879347-52bc45fb-760f-4de6-81f6-fdffa690ac11.png)
![contactpagemobile](https://user-images.githubusercontent.com/81080746/183879395-8d50dc13-a60a-458f-8525-e50ab37b24b8.png)
![contactpagemobile2](https://user-images.githubusercontent.com/81080746/183879445-7cf053d2-1da6-4640-aa15-9dc3b12b7b73.png)
