### ISSUE TITLE
Implement Privacy Policy Page Design

### ISSUE THREAD

**Issue by Waeyword** [zuri-training/Team-29_PriceCompare#21]

**Comment by Laurrencia** [comment]
The Privacy Policy Page was redesigned and i implemented the page design as well as responsive desktop and mobile view of the page

![privacypolicyredesign](https://user-images.githubusercontent.com/81080746/183881684-f040668d-17f9-42d2-8025-b0a58852029d.png)
![Screenshot (117)](https://user-images.githubusercontent.com/81080746/183881819-02c96f67-af4d-4d01-b3b0-7a25e3a86ef2.png)
![Screenshot (118)](https://user-images.githubusercontent.com/81080746/183881855-b66b4a33-61fe-453b-8712-2fafff5abf2c.png)
![Screenshot (120)](https://user-images.githubusercontent.com/81080746/183881898-709ea629-8d08-4aca-92c6-28d28c897442.png)
![Screenshot (119)](https://user-images.githubusercontent.com/81080746/183881943-86a97bc5-e837-42d1-bbdc-d3a5b9615cbd.png)
