### ISSUE TITLE
Implement Page Header and Footer Designs

### ISSUE THREAD

**Issue by Waeyword** [zuri-training/Team-29_PriceCompare#31]

**Comment by Laurrencia** [comment]
The Header and footer was redesigned and i implemented the new designs, as well as the responsive desktop and mobile view for the header and footer as well as the hamburger menu design


![Header](https://user-images.githubusercontent.com/81080746/183880562-5b4b3c6c-c375-4bf7-a1f8-32081284c73a.png)
![headermobile](https://user-images.githubusercontent.com/81080746/183880651-168c5810-2b69-4782-bb6f-cc4c5ea501c2.png)
![redesignfooter](https://user-images.githubusercontent.com/81080746/183880714-597fe876-77f6-4755-8c1d-bbb0da4d87fe.png)
![footermobile](https://user-images.githubusercontent.com/81080746/183880775-219fab95-64f6-46e9-b2ea-f429e83fae10.png)
![redesignfooter](https://user-images.githubusercontent.com/81080746/183880865-40fd2fa4-f001-4fbd-97c0-4d1899b6fb76.png)
