### ISSUE TITLE
Create Contact Page Design

### ISSUE THREAD

**Issue by Waeyword** [zuri-training/Team-29_PriceCompare#36]

**Comment by Ogecheem** [comment]
I redesigned the contact pages for both desktop and mobile in Hi-FI.
![CONTACT PAGE](https://user-images.githubusercontent.com/105248026/183925131-cc73ee8f-bd14-49c4-adaf-ee6bfc66df05.png)
<img width="390" alt="Contact us mobile view" src="https://user-images.githubusercontent.com/105248026/183925182-aef2bfe9-60c3-4b7e-863d-103e96dff4e1.png">
