### ISSUE TITLE
Implement Password Reset Page Design

### ISSUE THREAD

**Issue by Waeyword** [zuri-training/Team-29_PriceCompare#39]

**Comment by timmyades3** [comment]
I worked with frontend team to create the password reset pages
![password reset complete page Screenshot 2022-08-10 142629](https://user-images.githubusercontent.com/103801534/183913127-9a93ef56-e9bb-4a52-8a6e-3217a1ecd69e.png)
![password reset done page Screenshot 2022-08-10 142556](https://user-images.githubusercontent.com/103801534/183913138-368f1957-0abf-41f3-8f8b-5aeb720417f4.png)
![password reset form page Screenshot 2022-08-10 142520](https://user-images.githubusercontent.com/103801534/183913144-5c7d0097-d91b-4af7-9399-f83b64b03fd2.png)
![password reset page Screenshot 2022-08-10 142430](https://user-images.githubusercontent.com/103801534/183913151-4fddc180-9501-41cf-b9d7-ff7f41861fd8.png)
