### ISSUE TITLE
User Comment & Review System

### ISSUE THREAD

**Issue by Waeyword** [zuri-training/Team-29_PriceCompare#45]

**Comment by OjewaleKehinde** [comment]
Hello, I noticed you assigned comment and review system but I am and have
been working on is on data scraping and APIs. I do not know if this is a
mix-up.

**Comment by Jheff4** [comment]
Na me be de do the work before o🌚😢

**Comment by Judekennywise** [comment]
I and Etinosa are the ones working on this. Contact Wallace to reassign you
