### ISSUE TITLE
Create Unsuccessful sign up error page (Hi Fi)

### ISSUE THREAD

**Issue by Waeyword** [zuri-training/Team-29_PriceCompare#59]

**Comment by ireSeun** [comment]
i redesigned the unsuccessful sign up error page for mobile screen( Low fi and hi fi)
![Sign up notification](https://user-images.githubusercontent.com/82669341/183873241-7352e67d-36fe-46ab-917a-2535a1d2c107.png)
![Sign up error notification Lofi](https://user-images.githubusercontent.com/82669341/183873244-e53e6949-861e-43f0-9984-b846f5ccecdf.png)
