### ISSUE TITLE
Create Landing Page (Lo Fi)

### ISSUE THREAD

**Issue by Waeyword** [zuri-training/Team-29_PriceCompare#60]

**Comment by EmediongErnest** [comment]
![landing page mobile Loi fi](https://user-images.githubusercontent.com/109753907/183880720-ae179834-abfc-472b-a637-737d84aefd9e.png)
![LANDING PAGE (1)](https://user-images.githubusercontent.com/109753907/183880808-37d0ac35-bd1e-48bc-846c-6b0690448815.png)

**Comment by EmediongErnest** [comment]
I created landing page mobile and Desktop  (lo fi)
