### ISSUE TITLE
Create Sign Up Page (Lo Fi & Hi Fi)

### ISSUE THREAD

**Issue by Waeyword** [zuri-training/Team-29_PriceCompare#61]

**Comment by EmediongErnest** [comment]
I have done some new befitting  changes to the sign up and sign in pages 
so we can achieve the animate effect the developers are demanding for

**Comment by EmediongErnest** [comment]
![SIGN UP SCREEN](https://user-images.githubusercontent.com/109753907/183877828-4c2fb4e5-e1c6-4171-a4fc-6e69edc05bd2.png)
![SIGN UP SCREEN (1)](https://user-images.githubusercontent.com/109753907/183877887-cc71aa59-e511-4e54-b3d4-575471951ba2.png)

**Comment by EmediongErnest** [comment]
I designed the sign up page (lo fi) though the page was redesign by my team member, so I reflected the the new design on the hi fi. The same is applicable to the login page.
