### ISSUE TITLE
Create Sign In Page (Lo Fi & Hi Fi)

### ISSUE THREAD

**Issue by Waeyword** [zuri-training/Team-29_PriceCompare#62]

**Comment by EmediongErnest** [comment]
![SIGN IN SCREEN (1)](https://user-images.githubusercontent.com/109753907/183875003-65d33df4-f643-4d78-ae2c-197b9b5e0413.png)
![SIGN IN SCREEN (2)](https://user-images.githubusercontent.com/109753907/183875100-d0175f1f-af9f-4a70-9f87-f14bd04dc84d.png)

**Comment by EmediongErnest** [comment]
Sign in page lo fi and hi fi completed
