### ISSUE TITLE
Create About Us Page (Lo Fi & Hi Fi)

### ISSUE THREAD

**Issue by Waeyword** [zuri-training/Team-29_PriceCompare#63]

**Comment by EmediongErnest** [comment]
![About us lo fi](https://user-images.githubusercontent.com/109753907/183872653-ccaf8a63-8b5b-49d4-b102-3e948c2596ca.png)
![About us hi fi](https://user-images.githubusercontent.com/109753907/183872855-1ddc00db-ede5-4d4d-b9b7-74dc94b1f310.png)

**Comment by EmediongErnest** [comment]
These are the pictures of the about us that I designed
