### ISSUE TITLE
Create Landing Page (Hi Fi)

### ISSUE THREAD

**Issue by Waeyword** [zuri-training/Team-29_PriceCompare#64]

**Comment by okolofaith** [comment]
I designed the landing page prior to the first submissio
![LANDING PAGE ( hi fi)](https://user-images.githubusercontent.com/109824643/183865284-94ca0ac4-e4dd-4f90-a472-a22e3325c933.jpg)
n

**Comment by Ogecheem** [comment]
I redesigned the landing page for desktop view(Hi-Fi) after we received feedback based on our first presentation.
![LANDING PAGE ( hi fi) (1)](https://user-images.githubusercontent.com/105248026/183923255-a54e5c69-03a0-4bd4-92ce-b325f2f86156.jpg)
