### ISSUE TITLE
Create FAQ Page (Lo Fi) 

### ISSUE THREAD

**Issue by Waeyword** [zuri-training/Team-29_PriceCompare#65]

**Comment by ireSeun** [comment]
redesigned the FAQ page after first presentation feedback from our supervisor.
![Mobile FAQ lofi](https://user-images.githubusercontent.com/82669341/183857728-14ba6c2e-b3af-4a62-9ed3-9e4b0e570a34.png)
![Mobile FAQ (1)](https://user-images.githubusercontent.com/82669341/183857737-fa35acaa-b68d-40f1-af9b-33091c70b5f6.png)

**Comment by okolofaith** [comment]
I designed the low Fidelity desktop for the FAQ page prior to the first submission
![FAQ PAGE](https://user-images.githubusercontent.com/109824643/183864402-f2223094-76f0-4256-aba3-ce3f0c7268f6.png)
.

**Comment by Ogecheem** [comment]
I redesigned the FAQ page (HI-FI) for desktop view, making sure that there were no words written in blue colour apart from links based on the feedback from our supervisor.
![FAQ PAGE](https://user-images.githubusercontent.com/105248026/183920629-c9afbc40-f5a2-447b-b206-cfec35ee726e.png)
