### ISSUE TITLE
Create Product Page (Hi Fi) 

### ISSUE THREAD

**Issue by Waeyword** [zuri-training/Team-29_PriceCompare#67]

**Comment by snrchieftegz** [comment]
I created the hifi page for the electronic category of the product page

**Comment by Waeyword** [comment]
Other assignees: @snrchieftegz

**Comment by Gbobieclaire** [comment]
I updated the product page category of Computers and Kids and Toys 
I added images, components, content and other elements to create high fidelity mockup.

**Comment by ireSeun** [comment]
I created the product page category for iphones
I added images, components, content and other elements to create high fi and lofi page
created all the mobile screen three category/product page we have in both hi fi and lo fi
![Sub product page for specific search](https://user-images.githubusercontent.com/82669341/183875496-ac52a450-5e1d-479b-934c-596969bb919b.png)
![Computers (1)](https://user-images.githubusercontent.com/82669341/183875514-aa24eee0-4f89-49b9-9288-dd7e78ece644.png)
![Electronics (1)](https://user-images.githubusercontent.com/82669341/183875518-faaf28f4-46b7-4b32-8b36-b8c9e7173487.png)
![Search result for iphone mobile lofi (1)](https://user-images.githubusercontent.com/82669341/183875604-aaf0e0bf-24d3-4b5d-891f-92dcd838ac60.png)
