### ISSUE TITLE
Create Successful sign up notification page (Lo Fi) 

### ISSUE THREAD

**Issue by Waeyword** [zuri-training/Team-29_PriceCompare#69]

**Comment by mistadane** [comment]
Completed

**Comment by mistadane** [comment]
This page containing a form notifies users to login in order to proceed to the next phase


![WhatsApp Image 2022-08-10 at 10 04 55 AM](https://user-images.githubusercontent.com/40105485/183963893-5753ea0b-b580-4187-b684-92a4ef1bb9b4.jpeg)
