### ISSUE TITLE
Create Unsuccessful sign up error page (Lo Fi)

### ISSUE THREAD

**Issue by Waeyword** [zuri-training/Team-29_PriceCompare#70]

**Comment by mistadane** [comment]
I design the hi-fi or the sign up error page. this notify users to create an account on the platform before proceeding to the next step
![WhatsApp Image 2022-08-10 at 10 03 05 AM](https://user-images.githubusercontent.com/40105485/183963128-a6288fae-2f78-4d8f-9429-a5899e0987d5.jpeg)
.
