### ISSUE TITLE
Create Price Comparison Page (Lo Fi & Hi Fi) (Desktop & Mobile) 

### ISSUE THREAD

**Issue by Waeyword** [zuri-training/Team-29_PriceCompare#90]

**Comment by Gbobieclaire** [comment]
I designed the low Fi and High fi of the comparison page. It shows the product details, photos attachments, comment and review section, other best offers and a quick browse section.
I also designed comparison pages for each of the product in the Electronic product category and iphone category (24pages) 
![Screenshot (34).png](https://user-images.githubusercontent.com/109790387/183802437-def16810-f257-428f-8c92-d2c1acb4266d.png)
![Screenshot (33).png](https://user-images.githubusercontent.com/109790387/183802470-e5190f84-9457-4fc5-ad34-c64e3044002a.png)

**Comment by ireSeun** [comment]
Redesigned the price comparison pages and created the template for the redesigned pages for my team members(designers) to replicate while working on other price comparison pages for both destop and mobile screen
![Frame 1154 (1)](https://user-images.githubusercontent.com/82669341/183856406-047fb885-2a05-4c28-9452-dac0bde7650a.png)
![compare page 28](https://user-images.githubusercontent.com/82669341/183856695-94dbeee1-59c3-4051-b357-7460f2841974.png)

**Comment by Stefan1100** [comment]
I designed the mobile screen pages for the products in the computer category of the comparison page (12 Pages). The page consists of the product details, photos attachments, comment and review section, other best offers, and a quick browse section.
![2022-08-10](https://user-images.githubusercontent.com/105198218/183868941-4322f22f-7da1-4eaa-b84e-d9893ce08d13.png)

**Comment by okolofaith** [comment]
I designed compare pages screen 2,3,4,5,6,7 and 
![compare ppage](https://user-images.githubusercontent.com/109824643/183873544-bea5eeed-0eed-451e-8a95-0a5b2f22076b.PNG)
8

**Comment by PriscillaOore** [comment]
I designed the desktop screen pages for the products in the computer category of the comparison page (Pages 32, 34, 36,37). 
The page consists of the product description, photos attachments, comment and review section as well as other offers with their respective prices.

**Comment by EmediongErnest** [comment]
I redesigned the desktop screen pages for the products in the category of the comparison page (Pages8,9, 46,50).
Page 8 and 9 is the Electronics pages category while 46, 50 is on the iPhone category respectively.
![chrome_1vj4wmY7U2](https://user-images.githubusercontent.com/109753907/183885535-77d29060-9192-44c4-a626-3ebb6ca38abd.png)

![compare page 8](https://user-images.githubusercontent.com/109753907/183883766-f2b13406-43ab-47e3-8a05-0174bc879735.png)

**Comment by omojowobusola** [comment]
I designed the mobile screen pages for the products in the mobile category of the comparison page.

I also designed the desktop screen pages for the products in the desktop category of the comparison page(Specifically pages, 38,39,40,41,42,43,44,45).
![file1](https://user-images.githubusercontent.com/54557552/183943747-8d48dbee-b234-4f69-b4ea-cc77c80cca8d.png)
![file 2](https://user-images.githubusercontent.com/54557552/183943869-90aa6052-204f-4fa7-bddb-3c1a33f7d3a7.png)
