### ISSUE TITLE
Create Documentation Page (Lo Fi & Hi Fi) (Desktop & Mobile) 

### ISSUE THREAD

**Issue by Waeyword** [zuri-training/Team-29_PriceCompare#91]

**Comment by Stefan1100** [comment]
![Documentations (1)](https://user-images.githubusercontent.com/105198218/183844092-493c48ff-103f-4423-8aec-840e0ab71b04.jpg)
![Documentations](https://user-images.githubusercontent.com/105198218/183844105-635fa936-b797-4c0c-9c02-733853980bf6.jpg)
![Documentations Page](https://user-images.githubusercontent.com/105198218/183844108-2d4eae37-847e-4f74-b88f-34fd171bebdd.jpg)
I designed the low-fi and hi-fi documentation page for both mobile and desktop screen.
