### ISSUE TITLE
Create Password Reset Page (Lo-Fi and Hi-Fi) (Desktop and Mobile) 

### ISSUE THREAD

**Issue by Waeyword** [zuri-training/Team-29_PriceCompare#92]

**Comment by ireSeun** [comment]
redesigned the password reset page for mobile screens both high fi and lofi pages
![Password reset email notification](https://user-images.githubusercontent.com/82669341/183869187-5f3ce9d9-2ea3-4aaf-b7a8-76315da06e51.png)
![Password reset (3)](https://user-images.githubusercontent.com/82669341/183869189-f4695229-297e-472c-bbc8-bfc170ac5687.png)
![Password reset success (1)](https://user-images.githubusercontent.com/82669341/183869195-4566af16-321b-4fb2-821a-a4eec14a289d.png)
![Password reset (2)](https://user-images.githubusercontent.com/82669341/183869197-896501c6-f5ce-436d-8acd-5f763d303276.png)
![Password reset (1)](https://user-images.githubusercontent.com/82669341/183869199-6b521d36-73e2-48b0-974a-b7bd46850805.png)
![Sign up notification (1)](https://user-images.githubusercontent.com/82669341/183869203-67e2313e-df7e-470a-98cb-e9657e22dfb7.png)
![Sign up notification Lofi](https://user-images.githubusercontent.com/82669341/183869208-f759e286-30f9-49f3-9ddc-35a093cec2ba.png)
![Password reset success Lofi](https://user-images.githubusercontent.com/82669341/183869214-54502d4e-d468-4ae1-9f13-56fd55473279.png)
![Password reset Lofi](https://user-images.githubusercontent.com/82669341/183869216-f7812247-0da0-426a-ba07-c94c61bd1f8f.png)

**Comment by Ogecheem** [comment]
I designed the password reset pages for desktop (Hi-Fi).
![Password Reset (2)](https://user-images.githubusercontent.com/105248026/183917212-ef7c1736-7665-4cba-9d8c-6293557c5b38.png)
![Password Reset (1)](https://user-images.githubusercontent.com/105248026/183917254-fd3db193-faf8-454f-b22a-419f730ece56.png)
![Password Reset](https://user-images.githubusercontent.com/105248026/183917291-fa67ed8b-bb68-4bbf-b675-ad2cf76134e0.png)
![Password Reset (3)](https://user-images.githubusercontent.com/105248026/183917336-25c7bb48-e243-4cb6-b9dd-c469097a6858.png)
