### ISSUE TITLE
Create Feedback Page (Lo-Fi and Hi-Fi) (Desktop) 

### ISSUE THREAD

**Issue by Waeyword** [zuri-training/Team-29_PriceCompare#93]

**Comment by ireSeun** [comment]
created the mobile screen for feedback page both high fi and low fi
![Mobile Feedback page](https://user-images.githubusercontent.com/82669341/183859485-5f65e433-584b-41f8-8d85-028f54f33167.png)
![Mobile Feedback page (1)](https://user-images.githubusercontent.com/82669341/183859972-0e616f2e-2aca-49c3-ab92-dd9c551c18ea.png)

**Comment by Ogecheem** [comment]
I designed the feedback page desktop view(Hi-Fi).
![Feedback Page](https://user-images.githubusercontent.com/105248026/183919572-a8dba18a-1d62-4c0b-bd53-de5939d7ef0a.png)
