### ISSUE TITLE
Redesign the footer (Desktop and Mobile) 

### ISSUE THREAD

**Issue by Waeyword** [zuri-training/Team-29_PriceCompare#94]

**Comment by ireSeun** [comment]
redesigned the footer for mobile screen both lofi and hi fi
![mobile footer lofi](https://user-images.githubusercontent.com/82669341/183878837-6fcbe41a-85dc-4f3b-8633-f1e92ab08414.png)
![Mobile footer hifi](https://user-images.githubusercontent.com/82669341/183878844-2bdebe2a-f207-4866-bb65-752550c9adc4.png)

**Comment by Ogecheem** [comment]
I redesigned the footer for the desktop screen (Hi-Fi and Lo-Fi) after the first submission. I also made an adjustment to the mobile footer (Hi-Fi).
![Footer Hifi](https://user-images.githubusercontent.com/105248026/183914915-d77504d0-faaf-4f00-bbdb-adf4ae56748a.png)
![Frame 969](https://user-images.githubusercontent.com/105248026/183915024-20c692a6-da92-44df-a1c9-850152c8f4c5.png)
